import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@/components/css/index'
import '@/components/css/vendors'
import VendorInit from "@/components/VendorInit";
import AosInit from "@/components/AosInit";
// === Vendor CSS (node_modules) ===

// Animations
import 'animate.css/animate.min.css'

// Icons
import '@fortawesome/fontawesome-free/css/all.min.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import 'feather-icons/dist/feather.css'
import 'flag-icons/css/flag-icons.min.css'

// DataTables
import 'datatables.net-bs5/css/dataTables.bootstrap5.min.css'

// Alerts
import 'sweetalert2/dist/sweetalert2.min.css'

// Editors & Inputs
import 'quill/dist/quill.snow.css'
import 'select2/dist/css/select2.min.css'
import '@yaireo/tagify/dist/tagify.css'
import 'emojionearea/dist/emojionearea.min.css'

// Date & Time Pickers
import 'flatpickr/dist/flatpickr.min.css'
import 'daterangepicker/daterangepicker.css'
import 'tui-date-picker/dist/tui-date-picker.css'
import 'tui-time-picker/dist/tui-time-picker.css'

// Calendar
import 'tui-calendar/dist/tui-calendar.css'

// jQuery Steps
import 'jquery-steps/demo/css/jquery.steps.css'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <VendorInit />
        <AosInit />
        {children}
      </body>
    </html>
  );
}
